Audio Compressor 기능 추가
kyechan99/chzzk-plus pull request #9
Opened 2023-12-24 17:08 UTC by Deepbluewarn

FrankerFaceZ 확장 프로그램에서 잘 사용하던 기능이라 구현해보았습니다.

2023-12-24 17:50 UTC, kyechan99 requested changes
안녕하세요 !
관심과 기여 정말 감사드립니다 😄😄
유용하고 재밌는 기능인것 같아요.

일단 두 개 코멘트를 달긴했는데
혹시 원래 사용하시던 기능도 구현해주신 것처럼 비디오 하단에  UI 가 존재하나요?

2023-12-24 17:50 UTC, kyechan99 commented on src/components/button/AudioCompressorButton/AudioCompressorButton.tsx
> +  const video = document.getElementsByTagName("video")[0];
같은 의미이긴 합니다만 `document.querySelector(".webplayer-internal-video")` 로 바꿔주세요!
이미 다른 video 들을 사용하는 컴포넌트는 이렇게 사용하고 있고, 이런 클래스 이름은 constants 에 따로 분리해서 개발하고자 해서요.

2023-12-24 17:50 UTC, kyechan99 commented on src/components/button/AudioCompressorButton/AudioCompressorButton.tsx
> +      Add compression
UI 출력은 한글이 어떨까 싶습니다.
트위치는 글로벌 플랫폼이라 그래도 치지직은 한국인 사용자 밖에 없어서 한글이 낫지 않을까요?

2023-12-25 03:39 UTC, Deepbluewarn commented on src/components/button/AudioCompressorButton/AudioCompressorButton.tsx
> +      Add compression
이 부분은 아이콘으로 수정했습니다. 

https://www.svgrepo.com/svg/505504/sound-2
https://www.svgrepo.com/svg/505772/sound-0

2023-12-25 03:40 UTC, Deepbluewarn commented on src/components/button/AudioCompressorButton/AudioCompressorButton.tsx
> +  const video = document.getElementsByTagName("video")[0];
수정했습니다.

2023-12-25 03:44 UTC, Deepbluewarn commented
![1](https://github.com/kyechan99/chzzk-plus/assets/17985903/6794baf1-d07f-4284-93a0-83855b0a7105)
![2](https://github.com/kyechan99/chzzk-plus/assets/17985903/ab083ace-da6a-412a-9ffa-e776cc161031)

FrankerFaceZ 는 트위치 플레이어 좌측 하단에 저렇게 버튼이 위치하고 있습니다.

비슷한 아이콘을 구해서 치지직 플레이어의 우측 하단 버튼에 추가했어요.

2023-12-25 05:20 UTC, merged